create table if not exists "__EFMigrationsHistory"
(
    "MigrationId"    varchar(150) not null
        constraint "PK___EFMigrationsHistory"
            primary key,
    "ProductVersion" varchar(32)  not null
);

alter table "__EFMigrationsHistory"
    owner to avnadmin;

create table if not exists "Brands"
(
    "BrandId"   integer generated by default as identity
        constraint "PK_Brands"
            primary key,
    "BrandName" text not null,
    "ImageUrl"  text
);

alter table "Brands"
    owner to avnadmin;

create table if not exists "OrderStatuses"
(
    "OrderStatusId"   integer generated by default as identity
        constraint "PK_OrderStatuses"
            primary key,
    "OrderStatusName" text not null
);

alter table "OrderStatuses"
    owner to avnadmin;

create table if not exists "Roles"
(
    "RoleId"   integer generated by default as identity
        constraint "PK_Roles"
            primary key,
    "RoleName" text not null
);

alter table "Roles"
    owner to avnadmin;

create table if not exists "Vouchers"
(
    "VoucherId"               integer generated by default as identity
        constraint "PK_Vouchers"
            primary key,
    "VoucherName"             text                     not null,
    "VoucherCode"             text                     not null,
    "VoucherDiscount"         integer                  not null,
    "VoucherStartDate"        timestamp with time zone not null,
    "VoucherEndDate"          timestamp with time zone not null,
    "MaxDiscount"             real                     not null,
    "IsDeleted"               boolean                  not null,
    "VoucherPriceRequirement" real    default 0        not null,
    "NumOfVoucher"            integer default 0        not null
);

alter table "Vouchers"
    owner to avnadmin;

create unique index if not exists "IX_Vouchers_VoucherCode"
    on "Vouchers" ("VoucherCode");

create table if not exists "Boxes"
(
    "BoxId"          integer generated by default as identity
        constraint "PK_Boxes"
            primary key,
    "BoxName"        text                  not null,
    "BoxDescription" text,
    "BrandId"        integer               not null
        constraint "FK_Boxes_Brands_BrandId"
            references "Brands"
            on delete cascade,
    "IsDeleted"      boolean default false not null,
    "SoldQuantity"   integer default 0     not null,
    "Rating"         real    default 0     not null
);

alter table "Boxes"
    owner to avnadmin;

create unique index if not exists "IX_Boxes_BoxName"
    on "Boxes" ("BoxName");

create index if not exists "IX_Boxes_BrandId"
    on "Boxes" ("BrandId");

create table if not exists "Users"
(
    "UserId"    integer generated by default as identity
        constraint "PK_Users"
            primary key,
    "Username"  text                  not null,
    "Password"  text                  not null,
    "Fullname"  text                  not null,
    "Phone"     text                  not null,
    "Email"     text                  not null,
    "RoleId"    integer               not null
        constraint "FK_Users_Roles_RoleId"
            references "Roles"
            on delete cascade,
    "Gender"    boolean default false not null,
    "IsActive"  boolean default false not null,
    "AvatarUrl" text,
    "IsDelete"  boolean default false not null
);

alter table "Users"
    owner to avnadmin;

create unique index if not exists "IX_Users_Email"
    on "Users" ("Email");

create index if not exists "IX_Users_RoleId"
    on "Users" ("RoleId");

create unique index if not exists "IX_Users_Username"
    on "Users" ("Username");

create table if not exists "BoxImages"
(
    "BoxImageId"  integer generated by default as identity
        constraint "PK_BoxImages"
            primary key,
    "BoxImageUrl" text    not null,
    "BoxId"       integer not null
        constraint "FK_BoxImages_Boxes_BoxId"
            references "Boxes"
            on delete cascade
);

alter table "BoxImages"
    owner to avnadmin;

create index if not exists "IX_BoxImages_BoxId"
    on "BoxImages" ("BoxId");

create table if not exists "BoxItems"
(
    "BoxItemId"          integer generated by default as identity
        constraint "PK_BoxItems"
            primary key,
    "BoxItemName"        text    not null,
    "BoxItemDescription" text    not null,
    "BoxItemEyes"        text    not null,
    "BoxItemColor"       text    not null,
    "AverageRating"      real    not null,
    "BoxId"              integer not null
        constraint "FK_BoxItems_Boxes_BoxId"
            references "Boxes"
            on delete cascade,
    "ImageUrl"           text    not null,
    "NumOfVote"          integer not null,
    "IsSecret"           boolean not null
);

alter table "BoxItems"
    owner to avnadmin;

create index if not exists "IX_BoxItems_BoxId"
    on "BoxItems" ("BoxId");

create table if not exists "Addresses"
(
    "AddressId"     integer generated by default as identity
        constraint "PK_Addresses"
            primary key,
    "Province"      text              not null,
    "District"      text              not null,
    "Ward"          text              not null,
    "AddressDetail" text,
    "UserId"        integer           not null
        constraint "FK_Addresses_Users_UserId"
            references "Users"
            on delete cascade,
    "Name"          text,
    "PhoneNumber"   text,
    "DistrictId"    integer default 0 not null,
    "Note"          text,
    "ProvinceId"    integer default 0 not null,
    "WardCode"      integer default 0 not null
);

alter table "Addresses"
    owner to avnadmin;

create index if not exists "IX_Addresses_UserId"
    on "Addresses" ("UserId");

create table if not exists "BlogPosts"
(
    "BlogPostId"      integer generated by default as identity
        constraint "PK_BlogPosts"
            primary key,
    "BlogPostTitle"   text                                                                   not null,
    "BlogPostContent" text                                                                   not null,
    "BlogPostImage"   text                                                                   not null,
    "UserId"          integer                                                                not null
        constraint "FK_BlogPosts_Users_UserId"
            references "Users"
            on delete cascade,
    "BlogCreatedDate" timestamp with time zone default '-infinity'::timestamp with time zone not null
);

alter table "BlogPosts"
    owner to avnadmin;

create index if not exists "IX_BlogPosts_UserId"
    on "BlogPosts" ("UserId");

create table if not exists "UserVotedBoxItems"
(
    "UserVotedBoxItemId" integer generated by default as identity
        constraint "PK_UserVotedBoxItems"
            primary key,
    "BoxItemId"          integer                  not null
        constraint "FK_UserVotedBoxItems_BoxItems_BoxItemId"
            references "BoxItems"
            on delete cascade,
    "UserId"             integer                  not null
        constraint "FK_UserVotedBoxItems_Users_UserId"
            references "Users"
            on delete cascade,
    "LastUpdated"        timestamp with time zone not null,
    "Rating"             integer                  not null
);

alter table "UserVotedBoxItems"
    owner to avnadmin;

create index if not exists "IX_UserVotedBoxItems_BoxItemId"
    on "UserVotedBoxItems" ("BoxItemId");

create index if not exists "IX_UserVotedBoxItems_UserId"
    on "UserVotedBoxItems" ("UserId");

create table if not exists "Orders"
(
    "OrderId"               integer generated by default as identity
        constraint "PK_Orders"
            primary key,
    "UserId"                integer                                                           not null
        constraint "FK_Orders_Users_UserId"
            references "Users"
            on delete cascade,
    "OrderCreatedAt"        timestamp with time zone                                          not null,
    "VoucherId"             integer
        constraint "FK_Orders_Vouchers_VoucherId"
            references "Vouchers",
    "PaymentMethod"         text                                                              not null,
    "TotalPrice"            numeric                                                           not null,
    "Revenue"               numeric                                                           not null,
    "AddressId"             integer
        constraint "FK_Orders_Addresses_AddressId"
            references "Addresses",
    "OpenRequest"           boolean                  default false                            not null,
    "RefundRequest"         boolean                  default false                            not null,
    "CurrentOrderStatusId"  integer                  default 0                                not null,
    "PaymentStatus"         text                     default ''::text                         not null,
    "JsonOrderModel"        jsonb,
    "IsEnable"              boolean                  default false                            not null,
    "ShippingFee"           numeric                  default 0                                not null,
    "DiscountAmount"        numeric                  default 0.0                              not null,
    "SubTotal"              numeric                  default 0.0                              not null,
    "IsReadyForShipBoxItem" boolean                  default false                            not null,
    "OrderUpdatedAt"        timestamp with time zone default (now() AT TIME ZONE 'UTC'::text) not null
);

alter table "Orders"
    owner to avnadmin;

create index if not exists "IX_Orders_AddressId"
    on "Orders" ("AddressId");

create index if not exists "IX_Orders_UserId"
    on "Orders" ("UserId");

create index if not exists "IX_Orders_VoucherId"
    on "Orders" ("VoucherId");

create table if not exists "OrderStatusDetails"
(
    "OrderId"              integer                  not null
        constraint "FK_OrderStatusDetails_Orders_OrderId"
            references "Orders"
            on delete cascade,
    "OrderStatusId"        integer                  not null
        constraint "FK_OrderStatusDetails_OrderStatuses_OrderStatusId"
            references "OrderStatuses"
            on delete cascade,
    "OrderStatusUpdatedAt" timestamp with time zone not null,
    "OrderStatusNote"      text,
    constraint "PK_OrderStatusDetails"
        primary key ("OrderId", "OrderStatusId")
);

alter table "OrderStatusDetails"
    owner to avnadmin;

create index if not exists "IX_OrderStatusDetails_OrderStatusId"
    on "OrderStatusDetails" ("OrderStatusId");

create table if not exists "AspNetRoles"
(
    "Id"               text not null
        constraint "PK_AspNetRoles"
            primary key,
    "Name"             varchar(256),
    "NormalizedName"   varchar(256),
    "ConcurrencyStamp" text
);

alter table "AspNetRoles"
    owner to avnadmin;

create unique index if not exists "RoleNameIndex"
    on "AspNetRoles" ("NormalizedName");

create table if not exists "AspNetUsers"
(
    "Id"                   text                     not null
        constraint "PK_AspNetUsers"
            primary key,
    "UserName"             varchar(256),
    "NormalizedUserName"   varchar(256),
    "Email"                varchar(256),
    "NormalizedEmail"      varchar(256),
    "EmailConfirmed"       boolean                  not null,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumber"          text,
    "PhoneNumberConfirmed" boolean                  not null,
    "TwoFactorEnabled"     boolean                  not null,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean                  not null,
    "AccessFailedCount"    integer                  not null,
    "FullName"             text    default ''::text not null,
    "IsActive"             boolean default false    not null,
    "Password"             text    default ''::text not null
);

alter table "AspNetUsers"
    owner to avnadmin;

create index if not exists "EmailIndex"
    on "AspNetUsers" ("NormalizedEmail");

create unique index if not exists "UserNameIndex"
    on "AspNetUsers" ("NormalizedUserName");

create table if not exists "AspNetRoleClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_AspNetRoleClaims"
            primary key,
    "RoleId"     text not null
        constraint "FK_AspNetRoleClaims_AspNetRoles_RoleId"
            references "AspNetRoles"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table "AspNetRoleClaims"
    owner to avnadmin;

create index if not exists "IX_AspNetRoleClaims_RoleId"
    on "AspNetRoleClaims" ("RoleId");

create table if not exists "AspNetUserClaims"
(
    "Id"         integer generated by default as identity
        constraint "PK_AspNetUserClaims"
            primary key,
    "UserId"     text not null
        constraint "FK_AspNetUserClaims_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    "ClaimType"  text,
    "ClaimValue" text
);

alter table "AspNetUserClaims"
    owner to avnadmin;

create index if not exists "IX_AspNetUserClaims_UserId"
    on "AspNetUserClaims" ("UserId");

create table if not exists "AspNetUserLogins"
(
    "LoginProvider"       text not null,
    "ProviderKey"         text not null,
    "ProviderDisplayName" text,
    "UserId"              text not null
        constraint "FK_AspNetUserLogins_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    constraint "PK_AspNetUserLogins"
        primary key ("LoginProvider", "ProviderKey")
);

alter table "AspNetUserLogins"
    owner to avnadmin;

create index if not exists "IX_AspNetUserLogins_UserId"
    on "AspNetUserLogins" ("UserId");

create table if not exists "AspNetUserRoles"
(
    "UserId" text not null
        constraint "FK_AspNetUserRoles_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    "RoleId" text not null
        constraint "FK_AspNetUserRoles_AspNetRoles_RoleId"
            references "AspNetRoles"
            on delete cascade,
    constraint "PK_AspNetUserRoles"
        primary key ("UserId", "RoleId")
);

alter table "AspNetUserRoles"
    owner to avnadmin;

create index if not exists "IX_AspNetUserRoles_RoleId"
    on "AspNetUserRoles" ("RoleId");

create table if not exists "AspNetUserTokens"
(
    "UserId"        text not null
        constraint "FK_AspNetUserTokens_AspNetUsers_UserId"
            references "AspNetUsers"
            on delete cascade,
    "LoginProvider" text not null,
    "Name"          text not null,
    "Value"         text,
    constraint "PK_AspNetUserTokens"
        primary key ("UserId", "LoginProvider", "Name")
);

alter table "AspNetUserTokens"
    owner to avnadmin;

create table if not exists "BoxOptions"
(
    "BoxOptionId"      integer generated by default as identity
        constraint "PK_BoxOptions"
            primary key,
    "BoxId"            integer               not null
        constraint "FK_BoxOptions_Boxes_BoxId"
            references "Boxes"
            on delete cascade,
    "BoxOptionName"    text                  not null,
    "OriginPrice"      numeric               not null,
    "DisplayPrice"     numeric               not null,
    "BoxOptionStock"   integer               not null,
    "IsDeleted"        boolean               not null,
    "IsOnlineSerieBox" boolean default false not null,
    "Rating"           real    default 0     not null
);

alter table "BoxOptions"
    owner to avnadmin;

create table if not exists "OnlineSerieBoxes"
(
    "OnlineSerieBoxId"     integer                  not null
        constraint "PK_OnlineSerieBoxes"
            primary key
        constraint "FK_OnlineSerieBoxes_BoxOptions_OnlineSerieBoxId"
            references "BoxOptions"
            on delete cascade,
    "PriceIncreasePercent" integer                  not null,
    "IsSecretOpen"         boolean                  not null,
    "Turn"                 integer                  not null,
    "MaxTurn"              integer default 0        not null,
    "PriceAfterSecret"     numeric default 0.0      not null,
    "IsPublished"          boolean default false    not null,
    "BasePrice"            numeric default 0.0      not null,
    "ImageUrl"             text    default ''::text not null
);

alter table "OnlineSerieBoxes"
    owner to avnadmin;

create index if not exists "IX_BoxOptions_BoxId"
    on "BoxOptions" ("BoxId");

create table if not exists "CurrentRolledItems"
(
    "CurrentRolledItemId" integer generated by default as identity
        constraint "PK_CurrentRolledItems"
            primary key,
    "OnlineSerieBoxId"    integer                                                                not null
        constraint "FK_CurrentRolledItems_OnlineSerieBoxes_OnlineSerieBoxId"
            references "OnlineSerieBoxes"
            on delete cascade,
    "BoxItemId"           integer                  default 0                                     not null
        constraint "FK_CurrentRolledItems_BoxItems_BoxItemId"
            references "BoxItems"
            on delete cascade,
    "CreatedAt"           timestamp with time zone default '-infinity'::timestamp with time zone not null,
    "IsDisable"           boolean                  default false                                 not null
);

alter table "CurrentRolledItems"
    owner to avnadmin;

create index if not exists "IX_CurrentRolledItems_OnlineSerieBoxId"
    on "CurrentRolledItems" ("OnlineSerieBoxId");

create index if not exists "IX_CurrentRolledItems_BoxItemId"
    on "CurrentRolledItems" ("BoxItemId");

create table if not exists "UserRolledItems"
(
    "UserRolledItemId" integer generated by default as identity
        constraint "PK_UserRolledItems"
            primary key,
    "UserId"           integer not null
        constraint "FK_UserRolledItems_Users_UserId"
            references "Users"
            on delete cascade,
    "BoxItemId"        integer not null
        constraint "FK_UserRolledItems_BoxItems_BoxItemId"
            references "BoxItems"
            on delete cascade,
    "IsCheckOut"       boolean not null,
    "OnlineSerieBoxId" integer not null
        constraint "FK_UserRolledItems_OnlineSerieBoxes_OnlineSerieBoxId"
            references "OnlineSerieBoxes"
            on delete cascade
);

alter table "UserRolledItems"
    owner to avnadmin;

create table if not exists "OrderItems"
(
    "OrderItemId"               integer generated by default as identity
        constraint "PK_OrderItems"
            primary key,
    "OrderId"                   integer                  not null
        constraint "FK_OrderItems_Orders_OrderId"
            references "Orders"
            on delete cascade,
    "Quantity"                  integer                  not null,
    "OrderPrice"                numeric                  not null,
    "IsFeedback"                boolean                  not null,
    "BoxOptionId"               integer
        constraint "FK_OrderItems_BoxOptions_BoxOptionId"
            references "BoxOptions"
            on delete cascade,
    "OpenRequestNumber"         integer default 0        not null,
    "OrderStatusCheckCardImage" text[]  default ARRAY []::text[],
    "NumOfRefund"               integer default 0        not null,
    "UserRolledItemId"          integer
        constraint "FK_OrderItems_UserRolledItems_UserRolledItemId"
            references "UserRolledItems",
    "RefundStatus"              text    default ''::text not null,
    "Note"                      text    default ''::text not null
);

alter table "OrderItems"
    owner to avnadmin;

create index if not exists "IX_OrderItems_OrderId"
    on "OrderItems" ("OrderId");

create index if not exists "IX_OrderItems_BoxOptionId"
    on "OrderItems" ("BoxOptionId");

create index if not exists "IX_OrderItems_UserRolledItemId"
    on "OrderItems" ("UserRolledItemId");

create table if not exists "Feedbacks"
(
    "FeedbackId"      integer generated by default as identity
        constraint "PK_Feedbacks"
            primary key,
    "UserId"          integer                  not null
        constraint "FK_Feedbacks_Users_UserId"
            references "Users"
            on delete cascade,
    "FeedbackContent" text                     not null,
    "UpdatedAt"       timestamp with time zone,
    "CreatedAt"       timestamp with time zone not null,
    "ImageUrl"        text                     not null,
    "OrderItemId"     integer                  not null
        constraint "FK_Feedbacks_OrderItems_OrderItemId"
            references "OrderItems"
            on delete cascade,
    "Rating"          real default 0           not null
);

alter table "Feedbacks"
    owner to avnadmin;

create index if not exists "IX_Feedbacks_UserId"
    on "Feedbacks" ("UserId");

create unique index if not exists "IX_Feedbacks_OrderItemId"
    on "Feedbacks" ("OrderItemId");

create index if not exists "IX_UserRolledItems_BoxItemId"
    on "UserRolledItems" ("BoxItemId");

create index if not exists "IX_UserRolledItems_OnlineSerieBoxId"
    on "UserRolledItems" ("OnlineSerieBoxId");

create index if not exists "IX_UserRolledItems_UserId"
    on "UserRolledItems" ("UserId");


